require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'

Style/Documentation:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
    '%r': '()'
Lint/AssignmentInCondition:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Rails/Blank:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Rails/EnumHash:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
