require: rubocop-rails

AllCops:
  Exclude:
    - 'app/controllers/admin_account/authentification/sessions_controller.rb'
    - 'app/controllers/user_account/authentification/*.rb'
    - 'app/interactors/synchronize_school_holidays.rb'
    - 'app/models/invitation.rb'
    - 'app/models/notification.rb'
    - 'app/models/venue.rb'
    - 'app/services/data_education_gouv.rb'
    - 'test/controllers/user_account/venues_controller_test.rb'
    - 'test/models/booking_test.rb'
    - 'test/models/invitation_test.rb'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
    '%r': '()'
Lint/AssignmentInCondition:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Rails/Blank:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Rails/EnumHash:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
